[package]
name = "blobber_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.2.0"
quick-xml = "0.37.1"
reqwest = "0.12.9"
roxmltree = "0.20.0"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"]}
